apiVersion: v1
kind: Secret
metadata:
  name: spring-boot-cloud-config-demo
type: Opaque
data:
  datasource.username: "change this to the database username in base64 encoded"
  datasource.password: "change this to the database passoword in base64 encoded"
  oci.authentication.user-id: "change this to the oci user ocid in base64 encoded"
  oci.authentication.fingerprint: "change this to the user auth token fingerprint in base64 encoded"
  oci.authentication.private-key: "change this to the user auth private key in base64 encoded"
  oci.authentication.passphrase: "change this to the user auth private key passphrase in base64 encoded"
  oci.authentication.profile: "change this to the user auth profile in base64 encoded"
  oci.vault.datasource.username-key: "change this to the vault datasource username secret ocid in base64 encoded"
  oci.vault.datasource.password-key: "change this to the vault datasource password secret ocid in base64 encoded"
