kind: ConfigMap
apiVersion: v1
metadata:
  name: spring-boot-cloud-config-demo
data:
  oci.instance.tenancy-id: "change this to the tenancy-id"
  oci.instance.region-id: "change this to the region-id"
  oci.vault.datasource.url-key: "change this to the vault datasource url secret ocid"
  datasource.url: "change this to the datasource url"
